name: Send build to the personal website repository

on:
  # Trigger the workflow on push
  push:
    branches: [ master ]
  # Allow manual triggering of this workflow
  workflow_dispatch:

jobs:
  dispatch:
    name: Send build to the main repository
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: himax16/himax16.github.io
          event-type: deploy-jekyll
          client-payload: |- 
            {
              "repository": "${{ github.repository }}"
            }
